# Generated by Django 4.2.11 on 2024-03-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_tabledetails_bookingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeBooking',
            field=models.TimeField(),
        ),
    ]
