# Generated by Django 4.2.11 on 2024-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_timebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notesBooking',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
